WITH RECURSIVE EMTPY_HOUR( HOUR , CNT) AS (
    SELECT 0 AS HOUR , 0 AS CNT
    UNION ALL
    SELECT HOUR + 1, 0 AS CNT 
    FROM EMTPY_HOUR
    WHERE HOUR < 23
)
SELECT HOUR, SUM(CNT) AS COUNT
FROM(
    SELECT HOUR(DATETIME) AS HOUR , 1 AS CNT
    FROM ANIMAL_OUTS
    UNION ALL
    SELECT HOUR, CNT
    FROM EMTPY_HOUR
    )T1
GROUP BY HOUR
ORDER BY HOUR